'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  ArrowRight,
  CheckCircle2,
  X,
  RotateCcw,
  Calendar,
  Clock,
  Zap,
  TrendingUp,
  Search,
  Filter,
  Check,
} from 'lucide-react';
import { useAppStore } from '@/lib/store';
import { StatusBadge } from '../ui/StatusBadge';
import { cn } from '@/lib/utils';
import { Recommendation } from '@/lib/types';

interface RecommendationsProps {
  showTitle?: boolean;
}

export function Recommendations({ showTitle = true }: RecommendationsProps) {
  const {
    recommendations,
    dismissRecommendation,
    applyRecommendation,
    restoreRecommendation,
    generateRecommendations,
    addTask,
  } = useAppStore();

  const [selectedRecId, setSelectedRecId] = useState<string | null>(null);
  const [filterImpact, setFilterImpact] = useState<'ALL' | 'HIGH' | 'MEDIUM' | 'APPLIED'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const selectedRec = recommendations.find((r) => r.id === selectedRecId);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      generateRecommendations();
      setIsGenerating(false);
      showToast('AI synthesized 3 fresh targeted recommendations based on latest telemetry!');
    }, 1200);
  };

  const handleApply = (rec: Recommendation) => {
    applyRecommendation(rec.id);
    setSelectedRecId(null);
    showToast(`Applied recommendation: "${rec.title}" (+2 Twin Health awarded!)`);
  };

  const handleAddToStudyPlan = (rec: Recommendation) => {
    addTask({
      title: rec.action,
      description: `${rec.title}: ${rec.description}`,
      priority: rec.impact === 'HIGH' ? 'HIGH' : 'MEDIUM',
      time: 20,
      estimatedTime: 20,
      dueDate: 'Today',
      completed: false,
      subject: rec.targetTopic || 'AI Recommendation',
    });
    showToast(`Added "${rec.action}" to AI Study Plan!`);
  };

  // Filter recommendations
  const filteredRecs = recommendations.filter((rec) => {
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      const match =
        rec.title.toLowerCase().includes(q) ||
        rec.description.toLowerCase().includes(q) ||
        rec.action.toLowerCase().includes(q);
      if (!match) return false;
    }

    if (filterImpact === 'APPLIED') {
      return rec.applied === true;
    }
    if (filterImpact === 'HIGH') {
      return !rec.applied && !rec.dismissed && rec.impact === 'HIGH';
    }
    if (filterImpact === 'MEDIUM') {
      return !rec.applied && !rec.dismissed && rec.impact === 'MEDIUM';
    }
    // 'ALL'
    return !rec.applied && !rec.dismissed;
  });

  const activeCount = recommendations.filter((r) => !r.applied && !r.dismissed).length;
  const highImpactCount = recommendations.filter((r) => !r.applied && !r.dismissed && r.impact === 'HIGH').length;
  const appliedCount = recommendations.filter((r) => r.applied).length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="relative rounded-2xl bg-[#111722] border border-white/5 p-6 shadow-xl"
    >
      {/* Toast Notification */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="absolute top-4 left-1/2 -translate-x-1/2 z-30 px-4 py-2 rounded-xl bg-primary/90 text-white text-xs font-semibold shadow-lg backdrop-blur flex items-center gap-2 border border-primary/40"
          >
            <Sparkles className="w-3.5 h-3.5 text-secondary animate-pulse" />
            <span>{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-xl bg-primary/10 text-primary">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-medium text-white">AI Recommendations</h3>
            <p className="text-xs text-muted-foreground">Autonomous guidance generated by your Digital Twin</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary/10 hover:bg-primary/20 border border-primary/20 text-primary hover:text-white text-xs font-semibold transition-all disabled:opacity-50"
          >
            <Zap className={cn('w-3.5 h-3.5', isGenerating && 'animate-spin text-secondary')} />
            <span>{isGenerating ? 'Synthesizing...' : 'Generate Fresh AI Insights'}</span>
          </button>

          <span className="text-xs px-2.5 py-1 rounded-full bg-primary/10 text-primary border border-primary/20 font-semibold">
            {activeCount} active
          </span>
        </div>
      </div>

      {/* Filter Tabs & Search */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-2.5 mb-4">
        <div className="flex items-center gap-1 p-1 rounded-xl bg-white/5 border border-white/5 overflow-x-auto">
          <button
            onClick={() => setFilterImpact('ALL')}
            className={cn(
              'px-2.5 py-1 rounded-lg text-xs font-medium transition-all whitespace-nowrap',
              filterImpact === 'ALL'
                ? 'bg-primary text-white shadow-sm'
                : 'text-muted-foreground hover:text-white'
            )}
          >
            Active ({activeCount})
          </button>
          <button
            onClick={() => setFilterImpact('HIGH')}
            className={cn(
              'px-2.5 py-1 rounded-lg text-xs font-medium transition-all whitespace-nowrap',
              filterImpact === 'HIGH'
                ? 'bg-red-400/20 text-red-400 border border-red-400/30'
                : 'text-muted-foreground hover:text-white'
            )}
          >
            High Impact ({highImpactCount})
          </button>
          <button
            onClick={() => setFilterImpact('MEDIUM')}
            className={cn(
              'px-2.5 py-1 rounded-lg text-xs font-medium transition-all whitespace-nowrap',
              filterImpact === 'MEDIUM'
                ? 'bg-amber-400/20 text-amber-400 border border-amber-400/30'
                : 'text-muted-foreground hover:text-white'
            )}
          >
            Medium Impact
          </button>
          <button
            onClick={() => setFilterImpact('APPLIED')}
            className={cn(
              'px-2.5 py-1 rounded-lg text-xs font-medium transition-all whitespace-nowrap',
              filterImpact === 'APPLIED'
                ? 'bg-emerald-400/20 text-emerald-400 border border-emerald-400/30'
                : 'text-muted-foreground hover:text-white'
            )}
          >
            Applied History ({appliedCount})
          </button>
        </div>

        <div className="relative min-w-[180px]">
          <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            type="text"
            placeholder="Search recommendations..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-[#0D111A] border border-white/5 rounded-xl pl-8 pr-3 py-1 text-xs text-white placeholder:text-muted-foreground focus:outline-none focus:border-primary"
          />
        </div>
      </div>

      {/* Recommendations List */}
      <div className="space-y-3">
        <AnimatePresence>
          {filteredRecs.map((rec, index) => (
            <motion.div
              key={rec.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ delay: index * 0.04 }}
              onClick={() => setSelectedRecId(rec.id)}
              className={cn(
                'p-4 rounded-xl bg-[#0D111A] border transition-all group cursor-pointer',
                rec.applied
                  ? 'border-emerald-500/20 bg-emerald-950/10'
                  : 'border-white/5 hover:border-primary/30'
              )}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className="text-sm font-semibold text-white group-hover:text-primary transition-colors">
                      {rec.title}
                    </span>
                    {rec.impact && <StatusBadge status={rec.impact} />}
                    {rec.applied && (
                      <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-400/20 text-emerald-400 font-semibold flex items-center gap-1">
                        <Check className="w-3 h-3" /> Completed
                      </span>
                    )}
                  </div>

                  <p className="text-xs text-muted-foreground leading-relaxed mb-3">
                    {rec.description}
                  </p>

                  <div className="flex items-center justify-between flex-wrap gap-2 pt-2 border-t border-white/5">
                    <div className="flex items-center gap-3 text-xs">
                      <div className="flex items-center gap-1.5 text-emerald-400 font-medium">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>{rec.confidence}% AI Confidence</span>
                      </div>
                      <div className="text-muted-foreground/70 flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        <span>{rec.timeToComplete || '15 min'}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-2">
                      {!rec.applied ? (
                        <>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleAddToStudyPlan(rec);
                            }}
                            className="text-xs text-muted-foreground hover:text-white px-2 py-1 rounded-lg hover:bg-white/5 transition-colors flex items-center gap-1"
                          >
                            <Calendar className="w-3 h-3 text-primary" />
                            <span className="hidden sm:inline">Schedule</span>
                          </button>

                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleApply(rec);
                            }}
                            className="flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-lg bg-primary/20 hover:bg-primary text-primary hover:text-white transition-all group-hover:shadow-md"
                          >
                            <span>{rec.action}</span>
                            <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
                          </button>
                        </>
                      ) : (
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            restoreRecommendation(rec.id);
                            showToast(`Restored "${rec.title}" to active recommendations.`);
                          }}
                          className="text-xs text-muted-foreground hover:text-white flex items-center gap-1 transition-colors"
                        >
                          <RotateCcw className="w-3 h-3" />
                          <span>Undo</span>
                        </button>
                      )}
                    </div>
                  </div>
                </div>

                {!rec.applied && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      dismissRecommendation(rec.id);
                      showToast(`Dismissed recommendation.`);
                    }}
                    title="Dismiss"
                    className="p-1 hover:bg-white/5 rounded-lg transition-colors text-muted-foreground hover:text-white flex-shrink-0"
                  >
                    <X className="w-4 h-4" />
                  </button>
                )}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {filteredRecs.length === 0 && (
          <div className="text-center py-10 rounded-xl bg-[#0D111A]/40 border border-white/5">
            <div className="text-3xl mb-2">✨</div>
            <p className="text-sm font-medium text-slate-200">
              {filterImpact === 'APPLIED'
                ? 'No applied recommendations yet.'
                : 'All recommended actions addressed for today!'}
            </p>
            <p className="text-xs text-muted-foreground mt-1">
              Click &ldquo;Generate Fresh AI Insights&rdquo; to analyze newly updated vectors.
            </p>
          </div>
        )}
      </div>

      {/* Action Execution Plan Modal */}
      <AnimatePresence>
        {selectedRec && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 15 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 15 }}
              className="w-full max-w-lg rounded-2xl bg-[#0D111A] border border-white/10 p-6 shadow-2xl relative max-h-[90vh] flex flex-col"
            >
              {/* Modal Header */}
              <div className="flex items-start justify-between pb-4 border-b border-white/5">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-primary/10 text-primary border border-primary/20">
                    <Sparkles className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-base font-semibold text-white">{selectedRec.title}</h4>
                    <div className="flex items-center gap-2 mt-1">
                      {selectedRec.impact && <StatusBadge status={selectedRec.impact} />}
                      <span className="text-xs text-emerald-400 font-medium">
                        {selectedRec.confidence}% Confidence
                      </span>
                    </div>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedRecId(null)}
                  className="p-1.5 rounded-lg hover:bg-white/10 text-muted-foreground hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Modal Content */}
              <div className="flex-1 overflow-y-auto py-4 space-y-4 pr-1">
                <div className="p-3.5 rounded-xl bg-white/5 border border-white/5">
                  <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground block mb-1">
                    AI Diagnostic Context
                  </span>
                  <p className="text-xs text-slate-200 leading-relaxed">{selectedRec.description}</p>
                </div>

                {/* Step-by-Step Action Plan */}
                <div className="p-4 rounded-xl bg-[#111722] border border-white/5 space-y-2.5">
                  <span className="text-xs font-semibold text-white block">
                    Execution Steps ({selectedRec.action}):
                  </span>
                  <div className="space-y-2 text-xs">
                    <div className="flex items-start gap-2 text-slate-300">
                      <span className="w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center flex-shrink-0 text-[11px] font-bold">
                        1
                      </span>
                      <span>Review prerequisite flashcards & synthesized concept breakdown.</span>
                    </div>
                    <div className="flex items-start gap-2 text-slate-300">
                      <span className="w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center flex-shrink-0 text-[11px] font-bold">
                        2
                      </span>
                      <span>Solve 3 targeted validation questions to calibrate cognitive retention.</span>
                    </div>
                    <div className="flex items-start gap-2 text-slate-300">
                      <span className="w-5 h-5 rounded-full bg-primary/20 text-primary flex items-center justify-center flex-shrink-0 text-[11px] font-bold">
                        3
                      </span>
                      <span>Re-sync digital twin vector metrics to verify mastery recovery.</span>
                    </div>
                  </div>
                </div>

                {/* Projected Impact */}
                <div className="p-3 rounded-xl bg-emerald-400/5 border border-emerald-400/20 flex items-center justify-between text-xs">
                  <span className="text-muted-foreground flex items-center gap-1.5">
                    <TrendingUp className="w-4 h-4 text-emerald-400" />
                    Projected Twin Improvement:
                  </span>
                  <span className="font-semibold text-emerald-400">+2 Health & Concept Lift</span>
                </div>
              </div>

              {/* Modal Footer */}
              <div className="pt-3 border-t border-white/5 flex items-center justify-between gap-2">
                <button
                  onClick={() => handleAddToStudyPlan(selectedRec)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-xs text-slate-200 font-medium transition-colors"
                >
                  <Calendar className="w-3.5 h-3.5 text-primary" />
                  <span>Schedule in Plan</span>
                </button>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setSelectedRecId(null)}
                    className="px-3 py-2 rounded-xl text-xs text-muted-foreground hover:text-white transition-colors"
                  >
                    Cancel
                  </button>
                  {!selectedRec.applied && (
                    <button
                      onClick={() => handleApply(selectedRec)}
                      className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary hover:bg-primary/90 text-white text-xs font-semibold shadow-md shadow-primary/20 transition-all"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>Apply Now</span>
                    </button>
                  )}
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
