'use client';

import { useAppStore } from '@/lib/store';
import { HairlineRule } from '@/components/ui/HairlineRule';
import { AlertTriangle, ShieldAlert, CheckCircle2, RotateCcw } from 'lucide-react';

export default function StudentAlertsPage() {
  const alerts = useAppStore((s) => s.alerts);
  const resolveAlert = useAppStore((s) => s.resolveAlert);

  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <div className="space-y-2">
        <span className="font-mono text-xs text-burgundy uppercase tracking-widest font-medium">
          01 / CRITICAL EARLY WARNING SYSTEM
        </span>
        <h1 className="font-baskerville italic font-normal text-4xl text-ink-0">
          Academic Risk & Vector Alerts
        </h1>
        <p className="text-sm text-ink-2 font-inter">
          Automated risk notifications generated by your digital twin telemetry.
        </p>
      </div>

      <HairlineRule variant="accent" className="bg-burgundy" />

      <div className="space-y-4">
        {alerts.map((alert) => (
          <div
            key={alert.id}
            className={`p-6 rounded-md border space-y-4 ${
              alert.type === 'CRITICAL'
                ? 'bg-burgundy-light border-burgundy/30'
                : 'bg-paper-0 border-paper-3'
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex items-center gap-3">
                <ShieldAlert className={`w-5 h-5 ${alert.type === 'CRITICAL' ? 'text-burgundy' : 'text-mustard'}`} />
                <div>
                  <h3 className="font-space font-bold text-base text-ink-0">{alert.title}</h3>
                  <span className="font-mono text-[10px] text-ink-3 uppercase">{alert.timestamp}</span>
                </div>
              </div>
              <span className={`text-[10px] font-mono px-2 py-0.5 rounded font-semibold uppercase ${
                alert.type === 'CRITICAL' ? 'bg-burgundy text-paper-0' : 'bg-mustard text-paper-0'
              }`}>
                {alert.impact} IMPACT
              </span>
            </div>

            <p className="text-xs text-ink-1 leading-relaxed">{alert.message}</p>

            {alert.remediation && (
              <div className="p-3 rounded bg-paper-0 border border-paper-3 space-y-1 text-xs">
                <span className="font-mono text-[10px] text-olive font-semibold uppercase block">
                  RECOMMENDED REMEDIATION ACTION
                </span>
                <p className="font-semibold text-ink-0">{alert.remediation.actionName}</p>
                <p className="text-ink-2">{alert.remediation.description}</p>
              </div>
            )}

            <div className="pt-2 border-t border-paper-3 flex justify-end">
              <button
                onClick={() => resolveAlert(alert.id)}
                disabled={alert.resolved}
                className="px-4 py-1.5 text-xs font-semibold rounded-sm bg-ink-0 text-paper-0 hover:bg-ink-1 transition-colors flex items-center gap-1.5 disabled:opacity-50"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>{alert.resolved ? 'Resolved' : 'Mark Resolved'}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
