import { Student, KnowledgeGap, StudyTask, Alert, Agent, Recommendation, Intervention, Course } from '@/lib/types';

export const mockStudent: Student = {
  id: 'STU-2024-089',
  name: 'Alex Vance',
  academicHealth: 82,
  riskLevel: 'LOW',
  attendance: 87,
  engagement: 76,
  learningVelocity: 81,
  gpa: 3.64,
  predictedGpa: 3.78,
  performance: 84,
  gaps: 3,
  lastActivity: 'Active 5m ago',
};

export const mockStudentsList: Student[] = [
  { id: '1', name: 'Aarav Sharma', academicHealth: 61, riskLevel: 'HIGH', attendance: 68, engagement: 59, learningVelocity: 62, gpa: 2.8, predictedGpa: 2.6, performance: 54, gaps: 4, lastActivity: 'Today' },
  { id: '2', name: 'Priya Patel', academicHealth: 82, riskLevel: 'MEDIUM', attendance: 78, engagement: 80, learningVelocity: 85, gpa: 3.5, predictedGpa: 3.6, performance: 72, gaps: 2, lastActivity: 'Today' },
  { id: '3', name: 'Rahul Singh', academicHealth: 91, riskLevel: 'LOW', attendance: 92, engagement: 94, learningVelocity: 90, gpa: 3.9, predictedGpa: 3.95, performance: 88, gaps: 1, lastActivity: 'Yesterday' },
  { id: '4', name: 'Sneha Reddy', academicHealth: 45, riskLevel: 'CRITICAL', attendance: 55, engagement: 48, learningVelocity: 41, gpa: 2.1, predictedGpa: 1.9, performance: 42, gaps: 6, lastActivity: '2 days ago' },
  { id: '5', name: 'Vikram Kumar', academicHealth: 76, riskLevel: 'MEDIUM', attendance: 71, engagement: 75, learningVelocity: 78, gpa: 3.3, predictedGpa: 3.4, performance: 68, gaps: 3, lastActivity: 'Today' },
  { id: '6', name: 'Ananya Roy', academicHealth: 88, riskLevel: 'LOW', attendance: 95, engagement: 89, learningVelocity: 87, gpa: 3.8, predictedGpa: 3.85, performance: 86, gaps: 1, lastActivity: 'Today' },
  { id: '7', name: 'Karan Malhotra', academicHealth: 52, riskLevel: 'HIGH', attendance: 60, engagement: 54, learningVelocity: 58, gpa: 2.4, predictedGpa: 2.3, performance: 50, gaps: 5, lastActivity: '3 days ago' },
  { id: '8', name: 'Diya Gupta', academicHealth: 94, riskLevel: 'LOW', attendance: 98, engagement: 96, learningVelocity: 94, gpa: 4.0, predictedGpa: 4.0, performance: 95, gaps: 0, lastActivity: 'Today' },
];

export const mockKnowledgeGaps: KnowledgeGap[] = [
  { id: 'gap-1', concept: 'Normalization (3NF & BCNF)', subject: 'DBMS', mastery: 42, previousMastery: 61, trend: 'DOWN' },
  { id: 'gap-2', concept: 'Transactions & ACID Isolation', subject: 'DBMS', mastery: 68, previousMastery: 72, trend: 'DOWN' },
  { id: 'gap-3', concept: 'SQL Joins & Subqueries', subject: 'DBMS', mastery: 84, previousMastery: 80, trend: 'UP' },
  { id: 'gap-4', concept: 'Deadlock Detection & Prevention', subject: 'Operating Systems', mastery: 51, previousMastery: 58, trend: 'DOWN' },
  { id: 'gap-5', concept: 'Virtual Memory & Paging', subject: 'Operating Systems', mastery: 79, previousMastery: 74, trend: 'UP' },
  { id: 'gap-6', concept: 'BGP Routing Protocols', subject: 'Computer Networks', mastery: 63, previousMastery: 67, trend: 'DOWN' },
  { id: 'gap-7', concept: 'TCP 3-Way Handshake', subject: 'Computer Networks', mastery: 88, previousMastery: 82, trend: 'UP' },
];

export const mockStudyTasks: StudyTask[] = [
  { id: '1', title: 'DBMS Normalization Review', description: 'Review 3NF & BCNF functional dependencies and solve practice set #4', priority: 'HIGH', dueDate: '09:00 - 09:40', completed: false, estimatedTime: 40, time: 40 },
  { id: '2', title: 'OS Deadlocks Simulation', description: 'Practice Bankers Algorithm and deadlock avoidance examples', priority: 'MEDIUM', dueDate: '11:00 - 11:30', completed: false, estimatedTime: 30, time: 30 },
  { id: '3', title: 'Personalized AI DBMS Quiz', description: 'Interactive 15-minute diagnostic test generated by AI Agent', priority: 'HIGH', dueDate: '18:00 - 18:30', completed: false, estimatedTime: 30, time: 30 },
  { id: '4', title: 'Computer Networks Subnetting', description: 'Read RFC 4632 and complete CIDR calculation worksheet', priority: 'LOW', dueDate: '20:00 - 20:25', completed: true, estimatedTime: 25, time: 25 },
];

export const mockAlerts: Alert[] = [
  { id: '1', type: 'WARNING', title: 'Attendance Risk', message: 'DBMS attendance has fallen to 72%. Minimum required is 75%.', impact: 'MEDIUM', timestamp: '2 hours ago', time: '2 hours ago', dismissed: false },
  { id: '2', type: 'WARNING', title: 'Knowledge Gap Detected', message: 'Your DBMS Normalization performance has declined across 2 consecutive assessments.', impact: 'HIGH', timestamp: '4 hours ago', time: '4 hours ago', dismissed: false },
  { id: '3', type: 'CRITICAL', title: 'Critical Academic Risk Warning', message: 'Two upcoming midterms overlap with identified weak topics (DBMS, OS Deadlocks).', impact: 'HIGH', timestamp: '1 day ago', time: '1 day ago', dismissed: false },
  { id: '4', type: 'INFO', title: 'Learning Velocity Increase', message: 'Your problem solving speed in SQL Queries has improved by 14% this week.', impact: 'LOW', timestamp: '2 days ago', time: '2 days ago', dismissed: false },
];

export const mockAgents: Agent[] = [
  { id: 'learning', name: 'Learning Analysis Agent', icon: '🧠', status: 'ACTIVE', currentTask: 'Analyzing concept mastery vectors and quiz results', task: 'Analyzing knowledge gaps', lastRun: '2 min ago', priority: 1 },
  { id: 'attendance', name: 'Attendance & Pattern Agent', icon: '📊', status: 'ACTIVE', currentTask: 'Monitoring lecture check-ins and lab attendance', task: 'Monitoring attendance', lastRun: '5 min ago', priority: 2 },
  { id: 'assignment', name: 'Assignment Deadline Agent', icon: '📝', status: 'PROCESSING', currentTask: 'Evaluating upcoming deadlines & workload spikes', task: 'Checking deadlines', lastRun: '10 min ago', priority: 3 },
  { id: 'quiz', name: 'Quiz Generator Agent', icon: '📋', status: 'WAITING', currentTask: 'Standby for student concept remediation request', task: 'Waiting for trigger', lastRun: '1 hour ago', priority: 4 },
  { id: 'time', name: 'Time Management Agent', icon: '⏰', status: 'ACTIVE', currentTask: 'Optimizing daily study schedule against energy peaks', task: 'Optimizing schedule', lastRun: '8 min ago', priority: 5 },
];

export const mockRecommendations: Recommendation[] = [
  { id: 'rec-1', agentId: 'learning', title: 'Focus on 3NF Decomposition', description: 'Your twin detected a 19% drop in DBMS Normalization questions. Review functional dependency transitive rules.', action: 'Start 15m Practice Module', confidence: 94, impact: 'HIGH', category: 'Remediation' },
  { id: 'rec-2', agentId: 'time', title: 'Shift Study Window to 09:00 AM', description: 'Your engagement metrics indicate 32% higher retention when practicing core algorithms during morning hours.', action: 'Reschedule Study Plan', confidence: 88, impact: 'MEDIUM', category: 'Productivity' },
  { id: 'rec-3', agentId: 'assignment', title: 'Early Submission for OS Lab 3', description: 'Deadlock avoidance simulator requires ~2.5 hrs. Starting today prevents deadline bottleneck with Networks quiz.', action: 'Open Lab Template', confidence: 91, impact: 'HIGH', category: 'Planning' },
  { id: 'rec-4', agentId: 'quiz', title: 'Take Adaptive Quiz on Transactions', description: 'Solidify ACID isolation levels before Friday midterm exam.', action: 'Launch Quiz', confidence: 85, impact: 'MEDIUM', category: 'Assessment' },
];

export const mockInterventions: Intervention[] = [
  { id: 'int-1', studentId: '4', studentName: 'Sneha Reddy', riskLevel: 'CRITICAL', type: 'MEETING', title: 'Urgent 1-on-1 Academic Advisory', description: 'Sneha has 6 critical knowledge gaps and attendance has dropped to 55%. Immediate intervention required.', status: 'PENDING', suggestedAction: 'Schedule Meeting with Department Advisor', date: 'Today' },
  { id: 'int-2', studentId: '1', studentName: 'Aarav Sharma', riskLevel: 'HIGH', type: 'TUTORING', title: 'Assign Peer Tutor for DBMS', description: 'Aarav scores < 45% in Normalization. Assigning high-performing peer (Rahul Singh).', status: 'PENDING', suggestedAction: 'Pair with Peer Tutor', date: 'Today' },
  { id: 'int-3', studentId: '7', studentName: 'Karan Malhotra', riskLevel: 'HIGH', type: 'QUIZ', title: 'Dispatch Remedial OS Quiz', description: 'Karan needs targeted practice on Memory Management before final evaluation.', status: 'DISPATCHED', suggestedAction: 'Send AI Remedial Module', date: 'Yesterday' },
  { id: 'int-4', studentId: '5', studentName: 'Vikram Kumar', riskLevel: 'MEDIUM', type: 'COUNSELING', title: 'Attendance Check-in', description: 'Attendance dipped below 75% cutoff line in two lab sections.', status: 'COMPLETED', suggestedAction: 'Automated Warning Dispatched', date: '3 days ago' },
];

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    name: 'Database Management Systems',
    code: 'DBMS-7X4K2',
    subject: 'DBMS',
    section: 'Section A',
    term: 'Fall 2026',
    schedule: 'Mon/Wed/Fri · 09:00–09:50',
    color: '#8B5CF6',
    studentIds: ['1', '2', '3', '4', '5', '6', '7', '8'],
    createdAt: '2026-07-12',
  },
];

export const mockHeatmapData = [
  { topic: 'DBMS: Normalization', critical: 14, weak: 22, proficient: 24 },
  { topic: 'DBMS: Transactions', critical: 6, weak: 18, proficient: 36 },
  { topic: 'OS: Deadlocks', critical: 18, weak: 24, proficient: 18 },
  { topic: 'OS: Memory Paging', critical: 4, weak: 14, proficient: 42 },
  { topic: 'CN: BGP Protocols', critical: 10, weak: 20, proficient: 30 },
  { topic: 'CN: Subnetting', critical: 2, weak: 12, proficient: 46 },
];
